# -*- coding: utf-8 -*-
"""ai_advenced_news_agent.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s4beD7ieYSNxEcVmt3vuVAqnvzoRaMSq
"""

from langchain.tools import tool
import requests
import feedparser
from langchain.agents import create_agent
from langchain_openai import ChatOpenAI
import os
from langchain_core.messages import HumanMessage
import streamlit as st   

@tool
def ai_news_tool(limit: int = 5) -> str:
    """
    Fetches the latest AI news from artificialintelligence-news.com RSS feed.

    Args:
        limit: Number of latest news items to return

    Returns:
        A string containing the latest AI news titles and links.
    """
    url = "https://www.artificialintelligence-news.com/feed/"
    headers = {"User-Agent": "Mozilla/5.0"}
    response = requests.get(url, headers=headers, timeout=5)
    feed = feedparser.parse(response.text)

    news_set = set()
    for entry in feed.entries[:limit]:
        news_set.add(f"{entry.title} - {entry.link}")

    return "\n".join(news_set) if news_set else "No AI news found."



@tool
def github_search_tool(query: str, limit: int = 5) -> str:
    """
    Searches GitHub repositories for a given query and returns the top results.

    Args:
        query: The search term to look for in GitHub repositories.
        limit: Maximum number of top repositories to return (default is 5).

    Returns:
        A string containing the repository full names and URLs, separated by new lines.
    """
    GITHUB_TOKEN = st.secrets["GITHUB_TOKEN"]
    headers = {"Authorization": f"token {GITHUB_TOKEN}"}
    url = "https://api.github.com/search/repositories"
    params = {"q": query, "sort": "stars", "order": "desc", "per_page": limit}

    response = requests.get(url, headers=headers, params=params)
    if response.status_code != 200:
        return f"Failed to fetch GitHub repos. Status code: {response.status_code}"

    data = response.json()
    items = data.get("items", [])
    if not items:
        return "No repositories found."

    result = [f"{repo['full_name']} - {repo['html_url']}" for repo in items]
    return "\n".join(result)


model = ChatOpenAI(
    model_name="gpt-4o-mini",
    temperature=0.7,
    openai_api_key=st.secrets["OPENAI_API_KEY"]
)


tools = [ai_news_tool, github_search_tool]


agent = create_agent(
    tools=tools,
    model=model,

)


st.sidebar.header("Select Tool & Options")
tool_option = st.sidebar.selectbox("Select a tool:", ("AI News", "GitHub Search"))
num_results = st.sidebar.number_input("Number of results (1-10):", 1, 10, 5)

if tool_option == "GitHub Search":
    tool_query = st.sidebar.text_input("Enter GitHub query:")
else:
    tool_query = st.sidebar.text_input("Optional keyword for AI News:")


if "chat_history" not in st.session_state:
    st.session_state.chat_history = []


st.header("AI News & GitHub Chat App")


user_message = st.text_area("Chat with the Agent:", "")

if st.button("Send Message") or st.sidebar.button("Search"):
    
    if st.sidebar.button("Search") and tool_query:
        if tool_option == "AI News":
            message_content = f"{tool_query} | tool:ai_news | limit:{num_results}"
        else:
            message_content = f"{tool_query} | tool:github_search | limit:{num_results}"
    else:
        message_content = user_message

   
    if message_content.strip() != "":
        result = agent.invoke({"messages": [HumanMessage(content=message_content)]})
        response_text = result['messages'][-1].content

        
        st.session_state.chat_history.append(("User", message_content))
        st.session_state.chat_history.append(("Agent", response_text))


for sender, msg in st.session_state.chat_history:
    if sender == "User":
        st.markdown(f"**You:** {msg}")
    else:
        st.markdown(f"**Agent:** {msg}")
