# -*- coding: utf-8 -*-
"""ai_advenced_news_agent.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s4beD7ieYSNxEcVmt3vuVAqnvzoRaMSq
"""

from langchain.tools import tool
import requests
import feedparser
from langchain.agents import create_agent
from langchain_openai import ChatOpenAI
import os
from langchain_core.messages import HumanMessage
import streamlit as st   


st.header("AI News App")
st.subheader("🔎 Tool Result:")

st.subheader("💬 Chat with Agent")


enter=st.header("first you enter API Key and github token")
if not enter: 
    st.error("pleaze enter  your keys")
github_token = st.text_input("Enter your GitHub Token", type="password")
openai_api_key=st.text_input("Enter your  api key", type="password")

model = None
agent = None
    

@tool
def ai_news_tool(limit: int = 5) -> str:
    """
    Fetches the latest AI news from artificialintelligence-news.com RSS feed.
    """
    url = "https://www.artificialintelligence-news.com/feed/"
    headers = {"User-Agent": "Mozilla/5.0"}
    response = requests.get(url, headers=headers, timeout=5)
    feed = feedparser.parse(response.text)

    news_set = set()
    for entry in feed.entries[:limit]:
        news_set.add(f"{entry.title} - {entry.link}")

    return "\n".join(news_set) if news_set else "No AI news found."


@tool
def github_search_tool(query: str, limit: int = 5) -> str:
    """
    Searches GitHub repositories using user-provided token.
    """
    if not github_token:
        return "Please provide your GitHub token in the sidebar."
    
    headers = {"Authorization": f"token {github_token}"}
    url = "https://api.github.com/search/repositories"
    params = {"q": query, "sort": "stars", "order": "desc", "per_page": limit}

    response = requests.get(url, headers=headers, params=params)
    
     if response.status_code == 401:  #
        return "⚠️ Invalid GitHub token! Please check your token."
    elif response.status_code != 200:
        return f"GitHub request failed with status {response.status_code}."
    
    data = response.json()
    items = data.get("items", [])
    if not items:
        return "No repositories found."
    
    return "\n".join([f"{repo['full_name']} - {repo['html_url']}" for repo in items])
    

if openai_api_key.strip():
    from langchain_openai import ChatOpenAI
    try:
        model = ChatOpenAI(
            model_name="gpt-4o-mini",
            temperature=0.7,
            openai_api_key=openai_api_key
        )
        
        _ = model.invoke([HumanMessage(content="Hello")])
    except Exception as e:
        st.error("⚠️ Invalid OpenAI API Key! Please check your key.")
        model = None
else:
    st.warning("OpenAI API key missing!")




tools = [ai_news_tool, github_search_tool]

if model:  
    agent = create_agent(tools=tools, model=model)




user_message = st.text_area("Your message:")

if st.button("Send Message"):
    if not openai_api_key.strip():
        st.warning("Cannot chat: OpenAI API key missing.")
    elif not github_token.strip():
        st.warning("Cannot search GitHub: token missing.")
    elif not user_message.strip():
        st.warning("Please type a message.")
    elif not model:
        st.warning("Agent not initialized. Your OpenAI key may be invalid.")
    else:
        try:
            result = agent.invoke({"messages": [HumanMessage(content=user_message)]})
            st.subheader("🤖 Agent Response:")
            st.write(result['messages'][-1].content)
        except Exception as e:
            st.error(f"⚠️ Something went wrong: {e}")
